### ISSUE TITLE
[FEATURE] Enable multi-file includes

### ISSUE THREAD

**Issue by karolkarolkarolkarol** [bitgrip/cattlectl#28]
In order to prevent super long includes in the project.yaml like 
```
includes:
  - file: includes/services/mongodb.yaml
  - file: includes/services/postgresql.yaml
  - file: includes/services/backend.yaml
  - file: includes/services/frontend.yaml
  - file: includes/services/mysql.yaml
  - file: includes/services/proxy.yaml
  - file: includes/services/tools.yaml

```
it would be nice to have something like

```
includes:
  - files:  includes/services/*
```

or

```
 includes:
   - folder: includes/services/
```

where in both cases, all underlying files would be included into the project.yaml
