### ISSUE TITLE
[BUG] Unable to authenticate using API key

### ISSUE THREAD

**Issue by jhoffmann** [bitgrip/cattlectl#31]
**Describe the bug**
I'm just trying to use the example dummy project and values.yaml, and I've setup my ~/.cattlectl.yaml correctly using my access/secret tokens.

**To Reproduce**
- cattlectl version v1.1.1
- Rancher Version 2.2.2
- Using cattlectl CLI linux binary
- Debug log output 

https://gist.github.com/jhoffmann/159e47cd87b3a637f7bd0b473ab0b142

Includes obfuscated output and cattlectl.yaml.

**Additional context**
I'm not sure if this is because we have the Okta plugin enabled on our rancher instance, however the fact that the Rancher CLI is able to connect and perform operations seems odd.

**Comment by wtschreiter** [comment]
Hi,

I try to investigate this problem and want to setup your scenario in our environment.

Could you please compare your `~/cattlectl.yaml` and your `~/.rancher/cli2.json`

If your `~/.rancher/cli2.json` looks like (prettified):
```json
{
  "Servers": {
    "rancherDefault": {
      "accessKey": "token-XXXXX",
      "secretKey": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
      "tokenKey": "token-XXXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
      "url": "https://ZZZZZZZZZZZZZZZZZZ",
      "project": "c-xxxxx:p-yyyyy",
      "cacert": ""
    }
  },
  "CurrentServer": "rancherDefault"
}
``` 

your `~/cattlectl.yaml` needs to look like:
```yaml
rancher:
  url: https://ZZZZZZZZZZZZZZZZZZ
  access_key: token-XXXXX
  secret_key: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
  cluster_id: c-xxxxx
```

could you please confirm this is the case?
