### ISSUE TITLE
[BUG] Scoped api key not working

### ISSUE THREAD

**Issue by erSitzt** [bitgrip/cattlectl#47]
Do you need a cluster wide api key or is it ok to use one created only for a single scope ?
If not limited to a scope it works, but if i limit to a single cluster it get this error.

**To Reproduce**
❯ cattlectl version
v1.3.0
❯ Rancher Version
2.3.5

```
ERRO[0000] Failed to create management client            error="Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=clusterID does not match] from [https://rancher.domain.de/v3]" rancher.url="https://rancher.domain.de"
FATA[0000] Failed to create management client, Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=clusterID does not match] from [https://rancher.domain.de/v3]  cluster-name=zentrale-dev project-name=System resouce-type=app

```

my two configs are identical except for the api token

```
---
rancher:
  url: https://rancher.domain.de
  access_key: token-cn5b4
  secret_key: verysecretkey1
  cluster_id: c-g7hnt
  cluster_name: zentrale-dev
---
rancher:
  url: https://rancher.domain.de
  access_key: token-gtbn6
  secret_key: verysecretkey2
  cluster_id: c-g7hnt
  cluster_name: zentrale-dev
```
