### ISSUE TITLE
[FEATURE] Support multiple project definitions in a single yaml

### ISSUE THREAD

**Issue by erSitzt** [bitgrip/cattlectl#48]
I tried writing my yaml files like i am used to in kubernetes and ran into this small problem.

This type of config should work...
```
---
api_version: v1.0
kind: Project
metadata:
  name: neo-test
namespaces:
  - name: neo-test
---
api_version: v1.0
kind: Project
metadata:
  name: eec-test
namespaces:
  - name: eec-test
```

I saw your `include` config, but i think it does not fit a list of maybe unrelated projects as there is no hierarchy in rancher projects.
And it seems its not possible to create an empty parent project.yaml that only includes multiple files/directories.
