### ISSUE TITLE
support hierachical usage of yaml in values.yaml

### ISSUE THREAD

**Issue by mmueller90** [bitgrip/cattlectl#6]
Currently, you can only use a flat format for defining keys in the values.yaml, it would be nice to use the hierachical features of yaml to reduce the key names.
Current values.yaml:
```
apiserver_healthcheck_enabled: false
apiserver_service_type: "ClusterIP"
apiserver_storage_etcd_persistence_enabled: true
apiserver_verbosity: 2
```
hierachical:
```
apiserver:
  healthcheck:
    enabled: false
  service:
    type: "ClusterIP"
  storage:
    etcd:
      persistence:
        enabled: true
  verbosity: 2
```

in the project.yaml the values should be referenced with the dot notation along the hierarchy path:
```
answers:
      apiserver.healthcheck.enabled: "{{ .apiserver.healthcheck.enabled}}"
```

**Comment by wtschreiter** [comment]
Have you tried it?
In our project we are already using structured yaml.
That is missing is to have environment variable support for structures.

```yaml
apiserver:
  healthcheck:
    enabled: false
```

should have a corresponding environment variable `APISERVER_HEALTHCHECK_ENABLED` what is still missing but simple to implement.
