### ISSUE TITLE
[BUG] api_version is not correct

### ISSUE THREAD

**Issue by XenGi** [bitgrip/cattlectl#61]
**Describe the bug**
I tried the given example with my rancher cluster and it doesn't work. The API version is not correct. I don't know how to find out what the correct version is.

**To Reproduce**
- cattlectl version: v2.0.0
- Rancher Version: v2.4.5
- I use cattlectl as commandline tool
- Debug log output from `cattlectl <command> -v1`.
  ```
  DEBU[0000] values dose not exists                        values-file=/home/xengi/phpipam_test/values.yaml
  FATA[0000] Unsupported api version v3                    apply_file=project.yaml
  ```
- The _simplest example project descriptor and scripts_ needed to
  reproduce the bug.
  ```
  ---
  api_version: v1.0
  kind: Project
  metadata:
    name: phpipam
  namespaces:
    - name: phpipam
  ```

**Expected behavior**
I would think that this yaml would create a project called phpipam and a namespace called phpipam.

**Additional context**
I already tried v3 as the api_version because this is what I see in some requests to rancher but that gave the same output.
